### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by dwayneroberts** [hoodiehq/hoodie-app-tracker#160]
https://tracker.hood.ie/ is currently down:

502 Bad Gateway
nginx/1.9.9

**Comment by gr2m** [comment]
@christophwitzko can you please have a look?

**Comment by christophwitzko** [comment]
@gr2m This is the error on the server:
```
> hoodie-app-tracker@ start /app
> hoodie "--bind-address" "0.0.0.0"

WARN The use of --bindAddress is deprecated. Use the --address option instead. 
/app/node_modules/@gar/hapi-json-api/node_modules/hoek/lib/index.js:713
exports.assert = function (condition, ...args) {
                                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/node_modules/@gar/hapi-json-api/lib/index.js:4:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start" "--" "--bind-address" "0.0.0.0"
npm ERR! node v5.12.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! hoodie-app-tracker@ start: `hoodie "--bind-address" "0.0.0.0"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hoodie-app-tracker@ start script 'hoodie "--bind-address" "0.0.0.0"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hoodie-app-tracker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     hoodie "--bind-address" "0.0.0.0"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hoodie-app-tracker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hoodie-app-tracker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
```

**Comment by gr2m** [comment]
okay I know what happened, `@gar/hapi-json-api` dropped support for Node < 8 in a fix version, I asked the new maintainer to release a fix version reverting the change and a new breaking version that drops the node version ... https://github.com/kjellmorten/hapi-json-api/commit/bbd135dbe80d818304a86354feaf24196f6d5aa6#comments

Can you set the server to be run with latest Node 8.9 LTS version?

**Comment by christophwitzko** [comment]
Fixed in https://github.com/hoodiehq/hoodie-app-tracker/commit/de54ae68f5f3e73172dbf73d93971eeba7e81292 ☺️ 
https://tracker.hood.ie/ is up again 🎉

**Comment by gr2m** [comment]
thanks a ton! Meanwhile a fix to hapi-json-api was shipped as well: https://github.com/kjellmorten/hapi-json-api/releases/tag/v2.0.5
