### ISSUE TITLE
Request password reset error

### ISSUE THREAD

**Issue by laurensiusadi** [hoodiehq/hoodie-app-tracker#187]
Environment:

- Windows 10 64bit
- Node v10.13.0

Steps to replicate

1. Clone repo
2. run `npm install --production`
3. `cp .hoodierc-example .hoodierc`
4. put correct username and password for gmail account in `.hoodierc`
5. `npm start`
6. open localhost:8080
7. sign up for an account
8. login then sign out
9. go to forgot password
10. type email and press send
11. Alert says `Internal Server ErrorError: An internal server error occurred`

Here's what my terminal says:
```
ERR! TypeError TypeError: Uncaught error: Cannot read property 'transport' of undefined
ERR! TypeError     at handler (D:\Dev\hoodie-app-tracker\node_modules\@hoodie\account-server\routes\requests.js:29:34)
ERR! TypeError     at Object.internals.handler (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\handler.js:101:51)
ERR! TypeError     at request._protect.run (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\handler.js:32:23)
ERR! TypeError     at module.exports.internals.Protect.internals.Protect.run (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\protect.js:60:12)
ERR! TypeError     at exports.execute (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\handler.js:26:22)
ERR! TypeError     at each (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\request.js:401:16)
ERR! TypeError     at iterate (D:\Dev\hoodie-app-tracker\node_modules\items\lib\index.js:36:13)
ERR! TypeError     at done (D:\Dev\hoodie-app-tracker\node_modules\items\lib\index.js:28:25)
ERR! TypeError     at Hoek.once (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\protect.js:50:16)
ERR! TypeError     at wrapped (D:\Dev\hoodie-app-tracker\node_modules\hoek\lib\index.js:879:20)
ERR! TypeError  2018-11-25T11:16:37.784Z Uncaught error: Cannot read property 'transport' of undefined { TypeError: Uncaught error: Cannot read property 'transport' of undefined
ERR! TypeError     at handler (D:\Dev\hoodie-app-tracker\node_modules\@hoodie\account-server\routes\requests.js:29:34)
ERR! TypeError     at Object.internals.handler (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\handler.js:101:51)
ERR! TypeError     at request._protect.run (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\handler.js:32:23)
ERR! TypeError     at module.exports.internals.Protect.internals.Protect.run (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\protect.js:60:12)
ERR! TypeError     at exports.execute (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\handler.js:26:22)
ERR! TypeError     at each (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\request.js:401:16)
ERR! TypeError     at iterate (D:\Dev\hoodie-app-tracker\node_modules\items\lib\index.js:36:13)
ERR! TypeError     at done (D:\Dev\hoodie-app-tracker\node_modules\items\lib\index.js:28:25)
ERR! TypeError     at Hoek.once (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\protect.js:50:16)
ERR! TypeError     at wrapped (D:\Dev\hoodie-app-tracker\node_modules\hoek\lib\index.js:879:20)
ERR! TypeError   stack:
ERR! TypeError    'TypeError: Uncaught error: Cannot read property \'transport\' of undefined\n    at handler (D:\\Dev\\hoodie-app-tracker\\node_modules\\@hoodie\\account-server\\routes\\requests.js:29:34)\n    at Object.internals.handler (D:\\Dev\\hoodie-app-tracker\\node_modules\\hapi\\lib\\handler.js:101:51)\n    at request._protect.run (D:\\Dev\\hoodie-app-tracker\\node_modules\\hapi\\lib\\handler.js:32:23)\n    at module.exports.internals.Protect.internals.Protect.run (D:\\Dev\\hoodie-app-tracker\\node_modules\\hapi\\lib\\protect.js:60:12)\n    at exports.execute (D:\\Dev\\hoodie-app-tracker\\node_modules\\hapi\\lib\\handler.js:26:22)\n    at each (D:\\Dev\\hoodie-app-tracker\\node_modules\\hapi\\lib\\request.js:401:16)\n    at iterate (D:\\Dev\\hoodie-app-tracker\\node_modules\\items\\lib\\index.js:36:13)\n    at done (D:\\Dev\\hoodie-app-tracker\\node_modules\\items\\lib\\index.js:28:25)\n    at Hoek.once (D:\\Dev\\hoodie-app-tracker\\node_modules\\hapi\\lib\\protect.js:50:16)\n    at wrapped (D:\\Dev\\hoodie-app-tracker\\node_modules\\hoek\\lib\\index.js:879:20)',
ERR! TypeError   domain:
ERR! TypeError    Domain {
ERR! TypeError      domain: null,
ERR! TypeError      _events:
ERR! TypeError       { removeListener: [Function: updateExceptionCapture],
ERR! TypeError         newListener: [Function: updateExceptionCapture],
ERR! TypeError         error: [Function: bound ] },
ERR! TypeError      _eventsCount: 3,
ERR! TypeError      _maxListeners: undefined,
ERR! TypeError      members: [] },
ERR! TypeError   domainThrown: true,
ERR! TypeError   isBoom: true,
ERR! TypeError   isServer: true,
ERR! TypeError   data: null,
ERR! TypeError   output:
ERR! TypeError    { statusCode: 500,
ERR! TypeError      payload: { errors: [Array], meta: [Object] },
ERR! TypeError      headers:
ERR! TypeError       { 'access-control-allow-origin': 'http://localhost:8080',
ERR! TypeError         'access-control-allow-credentials': 'true',
ERR! TypeError         'content-type': 'application/vnd.api+json' } },
ERR! TypeError   reformat: [Function],
ERR! TypeError   isDeveloperError: true }
Debug: internal, implementation, error
    TypeError: Uncaught error: Cannot read property 'transport' of undefined
    at handler (D:\Dev\hoodie-app-tracker\node_modules\@hoodie\account-server\routes\requests.js:29:34)
    at Object.internals.handler (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\handler.js:101:51)
    at request._protect.run (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\handler.js:32:23)
    at module.exports.internals.Protect.internals.Protect.run (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\protect.js:60:12)
    at exports.execute (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\handler.js:26:22)
    at each (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\request.js:401:16)
    at iterate (D:\Dev\hoodie-app-tracker\node_modules\items\lib\index.js:36:13)
    at done (D:\Dev\hoodie-app-tracker\node_modules\items\lib\index.js:28:25)
    at Hoek.once (D:\Dev\hoodie-app-tracker\node_modules\hapi\lib\protect.js:50:16)
    at wrapped (D:\Dev\hoodie-app-tracker\node_modules\hoek\lib\index.js:879:20)
```

**Comment by laurensiusadi** [comment]
I manage to get this works, but not quite a fix.
The cause is `.hoodierc` file is not used for the `options` here.
So I just put the config manually.

Inside `node_modules\@hoodie\account-server\routes\requests.js`
```
function requestRoutes (server, options, next) {
  var api = server.plugins.account.api

  // I copy this part from .hoodierc file
  options.notifications = {
    "from": "email@gmail.com",
    "transport": {
      "service": "gmail",
      "auth": {
        "user": "email@gmail.com",
        "pass": "password"
      }
    }
  }
  console.log('requestRoutes options:', options)

  var postRequestsRoute = {
    method: 'POST',
    path: '/requests',
    config: {
      auth: false,
      validate: {
        payload: validations.requestPayload,
        query: validations.requestQuery,
        failAction: joiFailAction
      }
    },
    handler: function (request, reply) {
      if (!options.notifications.transport) { // Here's where the previous error
        reply(Boom.create(503, 'Config missing: account.notifications.transport'))
        return
      }
       
       ...
```

Now we need to use the `rc` package to read config from `.hoodierc` and put it inside `options` parameters.

**Comment by howellba1** [comment]
I was able to implement the fix above to send through gmail - however gmail rejects the send.
I know gmail had a place to allow a location to send through but can't seem to find it?
How could I use a different email server or third party email service other than gmail?
